# Example sources.yml
# Define your data sources and targets here

sources:
  - name: sample_texts
    type: text
    source: sample_docs
    params:
      glob: '*.txt'
    chunk_size: 512
    chunk_overlap: 50
    embedding_model: all-MiniLM-L6-v2  # Optional, for future use
    target:
      type: file
      path: output/sample_texts_embedded.json

  - name: sample_web
    type: web
    source:
      - https://example.com
      - https://langchain.com
    chunk_size: 512
    chunk_overlap: 50
    embedding_model: all-MiniLM-L6-v2
    target:
      type: vectordb
      db_type: chroma
      path: output/sample_web_chroma

  - name: sample_pdfs
    type: pdf
    source: sample_docs
    params:
      glob: '*.pdf'
    chunk_size: 512
    chunk_overlap: 50
    embedding_model: all-MiniLM-L6-v2
    target:
      type: file
      path: output/sample_pdfs_embedded.json
